chore: remove old versions
tl;dr:

- gemspec says 2.0.0 is the minimum
- we have a development dependency on Rake v13
- Rake v13 requires Ruby 2.2

See of CI failures:

- https://github.com/wincent/wikitext/actions/runs/20468362575/job/58817590973

Can't use 2.1.9 because:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    rake (~> 13.0) was resolved to 13.0.6, which depends on
      ruby (>= 2.2)

    wikitext was resolved to 4.8, which depends on
      ruby (>= 2.0.0)
```

- https://github.com/wincent/wikitext/actions/runs/20468362575/job/58817590974

Can't use 2.0.0 because:

```
Bundler could not find compatible versions for gem "ruby":
  In Gemfile:
    ruby

    rake (~> 13.0) was resolved to 13.0.6, which depends on
      ruby (>= 2.2)

    wikitext was resolved to 4.8, which depends on
      ruby (>= 2.0.0)
```

- https://github.com/wincent/wikitext/actions/runs/20468362575/job/58817590972

Can't use 1.9.3 because:

```
Error: Error: Unavailable version 1.9.3-p551 for ruby on ubuntu-24.04
          You can request it at https://github.com/ruby/setup-ruby/issues
          Cause: Unexpected HTTP response: 404
```

And because I had forgotten, my gemspec says:

```
  s.required_ruby_version = '>= 2.0.0'
```