chore: remove unsupported versions
As listed here:

- https://github.com/ruby/setup-ruby

Because CI failed with:

```
Error: Error: Unavailable version 1.9.3-p551 for ruby on ubuntu-24.04
          You can request it at
          https://github.com/ruby/setup-ruby/issues
```

See: https://github.com/wincent/wikitext/actions/runs/20468185502/job/58817011339